/// Flutter icons ExpenseIncome
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExpenseIncome
///      fonts:
///       - asset: fonts/ExpenseIncome.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExpenseIncome {
  ExpenseIncome._();

  static const _kFontFam = 'ExpenseIncome';
  static const _kFontPkg = null;

  static const IconData investing = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData winner = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refund = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_method__1_ = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idea = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary__1_ = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart__1_ = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card__1_ = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beauty_treatment = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_box = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categories = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sale_2 = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scholarship = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transportation = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData console__1_ = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell__1_ = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mortarboard = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData technical_support = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cleaning_tools = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
