/// Flutter icons ExpenseIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExpenseIcons
///      fonts:
///       - asset: fonts/ExpenseIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExpenseIcons {
  ExpenseIcons._();

  static const _kFontFam = 'ExpenseIcons';
  static const _kFontPkg = null;

  static const IconData trousers = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoes = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high_heels = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dress = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parking = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fuel_station = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tent = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_service = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach_vacation = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_wash = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mountain = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData makeup = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nail_polish = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplane = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hair_washing = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guitar = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cupcake = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piano = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cream = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_cup = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint_palette = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spaguetti = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData university = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taco = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closet = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air_conditioner = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shower = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant_pot = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pacifier_3 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby_boy = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teddy_bear = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pram = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData woman = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dental_checkup = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData injection = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lotus_position = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elliptical = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playing_cards = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skiing = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowling = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tennis_racket = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_ball = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rugby_ball = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming_pool = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData console = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunscreen = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData powder = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cosmetic = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shampoo = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_method = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
