/// Flutter icons MenuIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuIcons
///      fonts:
///       - asset: fonts/MenuIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MenuIcons {
  MenuIcons._();

  static const _kFontFam = 'MenuIcons';
  static const _kFontPkg = null;

  static const IconData dashboard = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_3 = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_of_black_cover_closed = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_2 = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_sign_inside_a_black_circle = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
